# Generated by Django 5.1.1 on 2024-09-05 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(max_length=50, verbose_name='Статус заказа')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('products', models.ManyToManyField(related_name='orders', to='catalog.product', verbose_name='Товары')),
            ],
        ),
    ]
