# Generated by Django 5.1.1 on 2024-10-02 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('В ожидании', 'В ожидании'), ('В обработке', 'В обработке'), ('В дороге', 'В дороге'), ('Доставлен', 'Доставлен'), ('Отменен', 'Отменен')], default='В ожидании', max_length=50, verbose_name='Статус заказа')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая стоимость')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('contact_phone', models.CharField(default='', max_length=20, verbose_name='Контактный телефон')),
                ('delivery_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Время доставки')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='Уведомления по email')),
                ('telegram_notifications', models.BooleanField(default=False, verbose_name='Уведомления по Telegram')),
                ('complete', models.BooleanField(default=False, verbose_name='Заказ завершен')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена при покупке')),
            ],
        ),
    ]
