# Generated by Django 5.1.1 on 2024-10-02 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=50, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(max_length=50, verbose_name='Новый статус')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения')),
            ],
        ),
    ]
