# Generated by Django 5.1.1 on 2024-10-02 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.IntegerField(default=0, verbose_name='Общее количество продаж')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая выручка')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Средняя стоимость заказа')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_analytics', to='catalog.product', verbose_name='Букет')),
            ],
            options={
                'verbose_name': 'Аналитика продаж',
                'verbose_name_plural': 'Аналитика продаж',
            },
        ),
    ]
